{{-- Plakietka "AI" w prawym dolnym rogu zdjecia wygenerowanego przez AI.
     Rodzic musi miec position: relative — na zwyklym zdjeciu uzyj otoczki:
       <span class="ip-ai-wrap">
           <img src="..." alt="...">
           <x-ai-badge />
       </span>
     Zdjecie na cala szerokosc kolumny: <div class="ip-ai-wrap is-block">.
     Tam, gdzie kontener juz ma position: relative (np. .ip-step-media.is-photo,
     .ip-trust-card, .ip-invrow-media), wystarczy samo <x-ai-badge />.

     Wariant dobieramy do tego, co jest POD plakietka w prawym dolnym rogu:
       <x-ai-badge />         ciemna pigulka  — gdy rog zdjecia jest jasny,
       <x-ai-badge light />   jasna pigulka   — gdy rog jest ciemny (ciemne
                              zdjecie albo przyciemnienie, np. gradient karty).
     Jeden kolor na wszystkim gubil sie na polowie zdjec. --}}
@props(['light' => false])

@php
    $aiPl = app()->getLocale() !== 'en';
@endphp

<span {{ $attributes->merge(['class' => 'ip-ai-badge' . ($light ? ' is-light' : '')]) }} title="{{ $aiPl ? 'Zdjęcie wygenerowane przez AI' : 'AI-generated image' }}">AI<span class="visually-hidden"> – {{ $aiPl ? 'zdjęcie wygenerowane przez sztuczną inteligencję' : 'image generated by artificial intelligence' }}</span></span>
