-- Polskie wersje 14 pytan FAQ (podstrona /jak-kupic-mieszkanie).
-- Uzupelnienie do 2026_09_21_faq.sql, ktory zalozyl tabele `faqs` i wgral
-- tresc: 7 pytan polskich (nasze, na bazie starej podstrony) + 14 pytan
-- angielskich od klienta, bez polskich odpowiednikow. Klient przyslal
-- brakujace polskie wersje tych 14 — ten plik je dopisuje.
--
-- Rekordy dopasowywane po ANGIELSKIM pytaniu, nie po `id`: id na produkcji
-- moga byc inne niz lokalnie. Kazdy UPDATE dotyka dokladnie jednego wiersza.
--
-- Zmiana przy okazji: z pytan angielskich schodzi numer ("1. ", "2. " ...).
-- Numeracja byla artefaktem dokumentu Word, a akordeon jest teraz sortowany
-- przeciaganiem w CMS-ie — po zmianie kolejnosci numery i tak by klamaly.
-- Dodatkowo 7 starszych pytan polskich numerow nie ma, wiec na jednej liscie
-- wychodzilo 7 nienumerowanych i 14 numerowanych. Zeby numery zostawic,
-- wystarczy w kazdym UPDATE przywrocic je w kluczu "en".
--
-- Plik mozna bezpiecznie puscic drugi raz: warunek WHERE szuka pytania
-- Z numerem, wiec po pierwszym przebiegu zaden wiersz juz nie pasuje i nic
-- sie nie dzieje (0 rows matched).
--
-- Angielskie odpowiedzi sa przepisywane bez zmian (wprost z tabeli), zeby
-- kazdy wpis mial po tym pliku komplet obu jezykow w jednym miejscu.
--
-- UWAGA: plik zawiera polskie znaki, wiec importujemy go JAWNIE w utf8mb4:
--   mysql -u... -p... baza --default-character-set=utf8mb4 < 2026_09_21_faq_pl.sql
-- Bez tego przelacznika klient mysql na Windowsie bierze kodowanie z codepage
-- konsoli (cp852) i zapisuje podwojnie zakodowane krzaki.

-- 1. What does the developer standard include?
UPDATE `faqs`
SET `question` = '{"pl":"Co zawiera stan deweloperski mieszkania i co wchodzi w jego skład?","en":"What does the developer standard include?"}',
    `answer`   = '{"pl":"<p>Stan deweloperski nie ma jednej, odgórnej definicji prawnej, dlatego jego dokładny zakres zawsze określa standard deweloperski i umowa deweloperska. Standardowo przyjmuje się, że mieszkanie w stanie deweloperskim jest przygotowane do prac wykończeniowych (tzw. \\"pod klucz\\"). Zakres standardu deweloperskiego jest zależny od standardu inwestycji mieszkaniowej.</p>\\n<p>W skład naszego standardu wchodzą m.in. tynki maszynowe gipsowo-wapienne na ścianach, wylewki podłogowe, kompletne instalacje: elektryczna, wodno-kanalizacyjna oraz grzewcza wraz z grzejnikami, a także gniazdka kuchenne, Gniazdo RTV+LAN oraz instalacje Smart Home.</p>","en":"<p>There is no single legal definition of the developer standard, so its exact scope is always described in the developer specification and the development agreement. In general, an apartment delivered to the developer standard is ready for finishing work. The exact scope may vary depending on the standard of the residential development.</p>\\n                        <p>Our standard includes, among other things, machine-applied gypsum-lime plaster on the walls, floor screeds, complete electrical, water, sewage and heating systems with radiators, as well as kitchen sockets, an RTV + LAN socket and Smart Home installations.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '1. What does the developer standard include?';

-- 2. What should you check before signing a development agreement?
UPDATE `faqs`
SET `question` = '{"pl":"Umowa deweloperska – na co zwrócić uwagę przed jej podpisaniem?","en":"What should you check before signing a development agreement?"}',
    `answer`   = '{"pl":"<p>Analizując projekt dokumentu, jakim jest umowa deweloperska, należy sprawdzić przede wszystkim dokładny prospekt informacyjny, harmonogram wpłat oraz ostateczny termin przeniesienia własności nieruchomości. Kluczowe jest zweryfikowanie dokładnego metrażu i przynależności (balkon, komórka lokatorska, miejsce w hali garażowej) oraz standardu wykonania. Bezpieczny zakup nowego mieszkania od dewelopera gwarantuje podpisanie umowy wyłącznie w formie aktu notarialnego.</p>","en":"<p>Before signing a development agreement, you should carefully check the Information Prospectus, payment schedule and the final date for the transfer of ownership.</p>\\n                        <p>It is also important to check the exact size of the apartment, any additional areas or facilities included with it, such as a balcony, storage unit or parking space in the underground garage, as well as the finishing standard.</p>\\n                        <p>For a safe purchase of a new apartment from a developer, the development agreement must be signed in the form of a notarial deed.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '2. What should you check before signing a development agreement?';

-- 3. What additional costs are involved when buying an apartment from a developer?
UPDATE `faqs`
SET `question` = '{"pl":"Jakie są koszty dodatkowe przy zakupie mieszkania od dewelopera?","en":"What additional costs are involved when buying an apartment from a developer?"}',
    `answer`   = '{"pl":"<p>Kupując nowe mieszkanie z rynku pierwotnego, jesteś zwolniony z podatku od czynności cywilnoprawnych (PCC), który na rynku wtórnym wynosi 2%.</p>\\n<p>Istnieją jednak inne koszty dodatkowe przy zakupie mieszkania, o których trzeba pamiętać:</p>\\n<ul>\\n    <li><strong>Opłaty notarialne:</strong> taksa notarialna (dzielona po połowie między dewelopera a kupującego), opłaty za odpisy aktu oraz wpisy w księdze wieczystej.</li>\\n    <li><strong>Koszt wykończenia:</strong> budżet na doprowadzenie wnętrza ze stanu deweloperskiego do stanu pod klucz.</li>\\n</ul>","en":"<p>When buying a new apartment on the primary market, you do not pay the 2% tax on civil law transactions (PCC), which generally applies to purchases on the secondary market.</p>\\n                        <p>However, there are some additional costs to consider:</p>\\n                        <ul>\\n                            <li><strong>Notary fees</strong> – the notary fee is shared equally between the developer and the buyer. There are also costs for copies of the notarial deed and entries in the Land and Mortgage Register.</li>\\n                            <li><strong>Finishing costs</strong> – you should also plan a budget for finishing the apartment and making it ready to move into.</li>\\n                        </ul>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '3. What additional costs are involved when buying an apartment from a developer?';

-- 4. What happens during the technical inspection of an apartment and what should you check?
UPDATE `faqs`
SET `question` = '{"pl":"Jak wygląda odbiór mieszkania od dewelopera i na co uważać?","en":"What happens during the technical inspection of an apartment and what should you check?"}',
    `answer`   = '{"pl":"<p>Osobisty odbiór techniczny mieszkania to moment, w którym sprawdzasz zgodność lokalu z umową deweloperską i normami budowlanymi. Warto zabrać ze sobą poziomicę, dalmierz lub skorzystać z pomocy profesjonalnego inżyniera. Podczas odbioru należy uważać na: piony i kąty ścian, ewentualne rysy na szybach okiennych, sprawność wentylacji, poprawne rozmieszczenie punktów elektrycznych oraz jakość wykonania wylewek. Wszystkie zauważone usterki wpisuje się do protokołu odbioru, a deweloper ma ustawowy termin na ustosunkowanie się do uwag.</p>","en":"<p>The technical inspection is the moment when you check whether the apartment meets the conditions set out in the development agreement and complies with building standards.</p>\\n                        <p>It is a good idea to bring a spirit level and a laser distance meter or ask a professional engineer to assist you.</p>\\n                        <p>During the inspection, you should check the walls and angles, any scratches on the windows, ventilation, the location of electrical points and the quality of the floor screeds.</p>\\n                        <p>All defects should be recorded in the inspection report. The developer then has a statutory period to respond to the reported defects.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '4. What happens during the technical inspection of an apartment and what should you check?';

-- 5. Why choose a new apartment instead of one from the secondary market?
UPDATE `faqs`
SET `question` = '{"pl":"Dlaczego warto wybrać nowe mieszkanie z rynku pierwotnego, a nie z wtórnego?","en":"Why choose a new apartment instead of one from the secondary market?"}',
    `answer`   = '{"pl":"<p>Inwestycja w nowe mieszkania od dewelopera to przede wszystkim oszczędność czasu i pieniędzy na starcie oraz gwarancja nowoczesnego budownictwa. Mieszkania budowane są zgodnie z najnowszymi przepisami budowlanymi, spełniając rygorystyczne normy jakości. Wybierając rynek pierwotny, zyskujesz 5-letnią rękojmię na wady konstrukcyjne, nowoczesną architekturę, dostęp do podziemnych hal garażowych, cichobieżnych wind oraz energooszczędnych technologii (np. fotowoltaika, Smart Home). Dodatkowo, kupujesz lokal bez podatku PCC 2% i masz pełną swobodę aranżacji wnętrza od zera.</p>","en":"<p>Buying a new apartment from a developer can save you time and money at the start and gives you the benefits of modern construction.</p>\\n                        <p>New apartments are built according to current building regulations and strict quality standards. When you buy on the primary market, you benefit from a 5-year statutory warranty for defects, modern architecture, underground garages, quiet lifts and energy-saving technologies such as photovoltaic panels and Smart Home systems.</p>\\n                        <p>You also do not pay the 2% PCC tax and have complete freedom to design and finish your new interior from scratch.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '5. Why choose a new apartment instead of one from the secondary market?';

-- 6. How can you safely buy a new apartment? What is a Housing Escrow Account?
UPDATE `faqs`
SET `question` = '{"pl":"Jak bezpiecznie kupić nowe mieszkanie? Czym jest mieszkaniowy rachunek powierniczy?","en":"How can you safely buy a new apartment? What is a Housing Escrow Account?"}',
    `answer`   = '{"pl":"<p>Bezpieczeństwo środków klientów kupujących mieszkania deweloperskie chroni tzw. Ustawa Deweloperska. Wpłacane przez Ciebie pieniądze nie trafiają bezpośrednio na konto dewelopera, ale na mieszkaniowy rachunek powierniczy prowadzony przez bank. Bank uwalnia środki partiami (w przypadku rachunku otwartego) dopiero po zweryfikowaniu zakończenia danego etapu budowy przez niezależnego kontrolera, co całkowicie eliminuje ryzyko utraty kapitału.</p>","en":"<p>The money paid by customers buying new apartments is protected under the Developer Act.</p>\\n                        <p>Your payments do not go directly to the developer’s bank account. Instead, they are paid into a Housing Escrow Account managed by a bank.</p>\\n                        <p>In the case of an open escrow account, the bank releases the money to the developer in stages. Funds are released only after an independent inspector confirms that a specific stage of construction has been completed. This provides a high level of protection for the buyer’s money.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '6. How can you safely buy a new apartment? What is a Housing Escrow Account?';

-- 7. Can I make changes to the layout of my new apartment?
UPDATE `faqs`
SET `question` = '{"pl":"Czy w nowym mieszkaniu można wprowadzić własne zmiany lokatorskie?","en":"Can I make changes to the layout of my new apartment?"}',
    `answer`   = '{"pl":"<p>Tak, większość deweloperów umożliwia modyfikację projektu na wczesnym etapie budowy nieruchomości. Zmiany lokatorskie w stanie deweloperskim pozwalają dopasować układ wnętrza do własnych potrzeb. Najczęściej klienci decydują się na przesunięcie ścian działowych, zmianę układu instalacji elektrycznej (punkty świetlne, gniazdka) oraz modyfikację podejść wodno-kanalizacyjnych (np. zamiana wanny na prysznic). Zgłoszenie zmian na odpowiednim etapie pozwala uniknąć kosztownych przeróbek podczas późniejszego wykańczania wnętrz.</p>","en":"<p>Yes. Most developers allow buyers to make changes at an early stage of construction.</p>\\n                        <p>These changes allow you to adapt the apartment to your individual needs. The most common changes include moving partition walls, changing the location of electrical points such as lights and sockets, and modifying water and sewage connections, for example replacing a bathtub with a shower.</p>\\n                        <p>Making these changes early can help you avoid expensive modifications when finishing the apartment later.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '7. Can I make changes to the layout of my new apartment?';

-- 8. How much does it cost to finish an apartment per square metre?
UPDATE `faqs`
SET `question` = '{"pl":"Ile kosztuje wykończenie mieszkania w stanie deweloperskim pod klucz za m2?","en":"How much does it cost to finish an apartment per square metre?"}',
    `answer`   = '{"pl":"<p>To, ile kosztuje wykończenie mieszkania, zależy od wybranych materiałów oraz stawek ekipy remontowej. Przyjmuje się, że minimalny koszt wykończenia mieszkania za m2 w standardzie podstawowym zaczyna się od około 2000 zł za metr kwadratowy (wliczając robociznę i materiały). W segmencie premium, gdzie królują materiały wysokiej jakości i meble na wymiar, budżet ten może znacznie wzrosnąć.</p>","en":"<p>The cost of finishing an apartment depends on the materials you choose and the rates charged by the finishing company.</p>\\n                        <p>As a general estimate, basic finishing costs start at around <strong>PLN 2,000 per square metre</strong>, including labour and materials.</p>\\n                        <p>For premium interiors with high-quality materials and custom-made furniture, the total cost can be much higher.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '8. How much does it cost to finish an apartment per square metre?';

-- 9. How does buying a new apartment with a mortgage work?
UPDATE `faqs`
SET `question` = '{"pl":"Jak krok po kroku wygląda zakup nowego mieszkania na kredyt hipoteczny?","en":"How does buying a new apartment with a mortgage work?"}',
    `answer`   = '{"pl":"<p>Proces zakupu nieruchomości z udziałem banku można zamknąć w kilku przejrzystych krokach:</p>\\n<ol>\\n    <li>Badanie zdolności kredytowej u doradcy finansowego i wybór wymarzonego lokalu.</li>\\n    <li>Podpisanie umowy rezerwacyjnej z deweloperem.</li>\\n    <li>Złożenie wniosku o kredyt hipoteczny na mieszkanie deweloperskie wraz z dokumentacją techniczną od dewelopera.</li>\\n    <li>Podpisanie umowy deweloperskiej i umowy kredytowej w banku.</li>\\n    <li>Uruchomienie kredytu przez bank w transzach, zgodnie z postępem prac na budowie.</li>\\n</ol>","en":"<p>Buying an apartment with mortgage financing can be divided into a few simple steps:</p>\\n                        <ol>\\n                            <li>Check your mortgage eligibility with a financial advisor and choose your apartment.</li>\\n                            <li>Sign a reservation agreement with the developer.</li>\\n                            <li>Apply for a mortgage and submit the required technical documents provided by the developer.</li>\\n                            <li>Sign the development agreement and the mortgage agreement with the bank.</li>\\n                            <li>The bank releases the mortgage funds in stages according to the progress of construction.</li>\\n                        </ol>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '9. How does buying a new apartment with a mortgage work?';

-- 10. How long is the statutory warranty for a new apartment and what does it cover?
UPDATE `faqs`
SET `question` = '{"pl":"Ile wynosi rękojmia na nowe mieszkanie od dewelopera i co obejmuje?","en":"How long is the statutory warranty for a new apartment and what does it cover?"}',
    `answer`   = '{"pl":"<p>Na podstawie Kodeksu Cywilnego, rękojmia na nowe mieszkanie z rynku pierwotnego wynosi dokładnie 5 lat od dnia wydania lokalu kupującemu (podpisania protokołu odbioru). Odpowiedzialność dewelopera obejmuje wszelkie wady fizyczne nieruchomości. W przypadku wykrycia wady w tym okresie, właściciel ma prawo żądać od dewelopera naprawy usterki.</p>","en":"<p>Under the Polish Civil Code, the statutory warranty for a new apartment is <strong>5 years from the date the apartment is handed over to the buyer</strong>.</p>\\n                        <p>The developer is responsible for physical defects in the property. If a defect is discovered during this period, the owner has the right to ask the developer to repair it.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '10. How long is the statutory warranty for a new apartment and what does it cover?';

-- 11. How to choose an apartment for a single person?
UPDATE `faqs`
SET `question` = '{"pl":"Jak wybrać mieszkanie dla singla?","en":"How to choose an apartment for a single person?"}',
    `answer`   = '{"pl":"<p>Wybierając mieszkanie dla singla, warto postawić na kompaktowy metraż, taki jak funkcjonalna kawalereka lub małe mieszkanie 2-pokojowe. Kluczowa jest lokalizacja zapewniająca bliskość centrum, sprawne połączenia komunikacyjne oraz łatwy dostęp do punktów handlowo-usługowych. Dużym atutem są także systemy smart home, które znacząco podnoszą komfort i bezpieczeństwo użytkowania lokalu. Szukając idealnego M dla singla w Olsztynie, warto sprawdzić osiedle TEMPO przy ul. Sikorskiego, doskonale dopasowane do potrzeb dynamicznych osób.</p>","en":"<p>When choosing an apartment for one person, it is worth considering a compact and functional studio or a small one-bedroom apartment.</p>\\n                        <p>Location is very important. Good access to the city centre, public transport, shops and services makes everyday life easier.</p>\\n                        <p>Smart Home systems are also a great advantage, improving both comfort and security. If you are looking for an apartment for one person in Olsztyn, <strong>TEMPO at Sikorskiego Street</strong> is a good option for people with an active lifestyle.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '11. How to choose an apartment for a single person?';

-- 12. What should an apartment for a senior offer?
UPDATE `faqs`
SET `question` = '{"pl":"Jakie powinno być mieszkanie dla seniora?","en":"What should an apartment for a senior offer?"}',
    `answer`   = '{"pl":"<p>Mieszkanie dla seniora musi być bezpieczne, funkcjonalne i całkowicie pozbawione barier architektonicznych. Kluczowym udogodnieniem jest nowoczesna winda zjeżdżająca bezpośrednio do garażu podziemnego i komórek lokatorskich oraz wejścia do budynku z poziomu terenu. Równie ważna jest bliskość przychodni, aptek, sklepów i przystanków komunikacji miejskiej. Osiedle dla osoby starszej powinno oferować także ciche, zielone patio z ławkami oraz monitoring podnoszący poczucie bezpieczeństwa.</p>","en":"<p>An apartment for a senior should be safe, functional and free from architectural barriers.</p>\\n                        <p>An important feature is a modern lift with direct access to the underground garage and storage units, as well as step-free access to the building.</p>\\n                        <p>Easy access to medical centres, pharmacies, shops and public transport is also important. A senior-friendly development should also offer quiet green areas with benches and monitoring for greater safety.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '12. What should an apartment for a senior offer?';

-- 13. What do families with children look for when choosing an apartment?
UPDATE `faqs`
SET `question` = '{"pl":"Czym kierują się rodziny z dziećmi przy wyborze mieszkania?","en":"What do families with children look for when choosing an apartment?"}',
    `answer`   = '{"pl":"<p>Priorytetem dla rodzin z dziećmi jest bezpieczeństwo, przestrzeń oraz bliskość szkół, przedszkoli, placówek medycznych i sklepów. Niezwykle ważne są monitorowane tereny zielone ze ścieżkami spacerowymi i boiskami, które sprzyjają aktywnemu spędzaniu czasu z najmłodszymi. Rodziny zwracają też uwagę na rozwiązania proekologiczne, które realnie obniżają codzienne rachunki. Doskonałym przykładem takiej inwestycji w Olsztynie jest osiedle SLOW, stworzone z myślą o wygodzie rodzin.</p>","en":"<p>For families with children, the main priorities are safety, space and easy access to schools, kindergartens, medical centres and shops.</p>\\n                        <p>Safe and monitored green areas with walking paths, playgrounds and sports areas are also very important, as they provide space for families to spend time outdoors.</p>\\n                        <p>Families also value environmentally friendly solutions that can help reduce everyday running costs. A good example in Olsztyn is the <strong>SLOW development</strong>, designed with family comfort in mind.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '13. What do families with children look for when choosing an apartment?';

-- 14. What green areas and shared facilities do modern residential developments offer?
UPDATE `faqs`
SET `question` = '{"pl":"Jakie udogodnienia terenów zielonych i części wspólnych oferują nowoczesne osiedla?","en":"What green areas and shared facilities do modern residential developments offer?"}',
    `answer`   = '{"pl":"<p>Nowoczesne osiedla stawiają na integrację i relaks mieszkańców, tworząc przemyślane strefy rekreacyjne w obrębie części wspólnych. Przykładowo na osiedlu SLOW w Olsztynie powstała plenerowa strefa do jogi, wiata grillowa ze stołami oraz profesjonalny tor agility dla psów. Do dyspozycji mieszkańców są również bezpieczne place zabaw, ogrody deszczowe, stacje ładowania pojazdów elektrycznych oraz wiaty rowerowe.</p>","en":"<p>Modern residential developments provide shared spaces designed for relaxation, recreation and spending time together.</p>\\n                        <p>For example, the <strong>SLOW development in Olsztyn</strong> offers an outdoor yoga area, a barbecue shelter with tables and a professional agility area for dogs.</p>\\n                        <p>Residents can also use safe playgrounds, rain gardens, electric vehicle charging stations and bicycle shelters.</p>"}'
WHERE JSON_UNQUOTE(JSON_EXTRACT(`question`, '$.en')) = '14. What green areas and shared facilities do modern residential developments offer?';
