-- Modul FAQ dla podstrony /jak-kupic-mieszkanie (Strefa Klienta).
-- Do tej pory pytania i odpowiedzi siedzialy na sztywno w widoku
-- resources/views/front/static/howbuy.blade.php, w tablicy $faq — osobnej
-- dla PL i EN. Teraz sa rekordami CMS-u: pytanie i odpowiedz tlumaczone
-- (JSON spatie/laravel-translatable), kolejnosc przeciaganiem wiersza.
--
-- Migracje Laravela sa nieaktualne (patrz 2026_09_17_investments_sort.sql),
-- zmiany schematu ida tedy.
--
-- UWAGA: plik zawiera polskie znaki, wiec importujemy go JAWNIE w utf8mb4:
--   mysql -u... -p... baza --default-character-set=utf8mb4 < 2026_09_21_faq.sql
-- Klient mysql na Windowsie bierze kodowanie z codepage konsoli (cp852) i bez
-- tego przelacznika zapisuje podwojnie zakodowane krzaki (wybrać -> wybra─ç).
CREATE TABLE `faqs` (
    `id`         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `question`   TEXT     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `answer`     LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `sort`       INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tresc przeniesiona 1:1 z widoku. PL i EN to DWA ROZNE ZESTAWY pytan
-- (7 polskich na bazie starej podstrony + 14 angielskich od klienta z pliku
-- "Jak kupic mieszkanie 09.2026.docx"), nigdy nie byly swoimi tlumaczeniami.
-- Dlatego kazdy rekord ma wypelniony tylko jeden jezyk, a front pomija wpisy
-- puste w aktywnym jezyku — dzieki temu PL dalej pokazuje swoje 7, a EN swoje
-- 14, dokladnie jak przed zmiana. Klient uzupelnia brakujace wersje w CMS-ie.
INSERT INTO `faqs` (`question`, `answer`, `sort`) VALUES
('{"pl":"Jak wybrać nowe mieszkanie? Od czego zacząć?"}', '{"pl":"Wybór nowego mieszkania to decyzja, której nie należy podejmować pochopnie – liczy się nie tylko cena, ale dziesiątki czynników wpływających na komfort życia przez kolejne lata. Zanim zaczniesz przeglądać oferty, warto określić swoje priorytety: co jest dla Ciebie absolutnie najważniejsze, a z czego jesteś w stanie zrezygnować. Dobrym punktem startowym jest odpowiedź na trzy fundamentalne pytania dotyczące lokalizacji, metrażu i budżetu."}', 1),
('{"pl":"Rynek pierwotny czy wtórny? Krótkie porównanie"}', '{"pl":"Mieszkanie z rynku pierwotnego kupujesz bez pośrednika i bez podatku od czynności cywilnoprawnych, w standardzie deweloperskim, który wykańczasz po swojemu. Budynek jest nowy, energooszczędny i objęty gwarancją oraz pięcioletnią rękojmią. Rynek wtórny daje szybsze wprowadzenie i znaną okolicę, ale zwykle wyższe koszty eksploatacji i konieczność remontu."}', 2),
('{"pl":"Zakup pierwszego mieszkania. Jak do tego podejść?"}', '{"pl":"Zacznij od budżetu: sprawdź zdolność kredytową i policz wkład własny razem z kosztami okołozakupowymi (notariusz, wpisy, wykończenie). Dopiero potem szukaj mieszkania – będziesz oglądać oferty, na które realnie Cię stać. Na każdym etapie możesz liczyć na naszego doradcę, który wytłumaczy zapisy umowy i przeprowadzi przez formalności."}', 3),
('{"pl":"Jak oglądać nowe mieszkanie? Praktyczny przewodnik"}', '{"pl":"Sprawdź układ pomieszczeń i to, czy meble, których używasz, zmieszczą się bez kompromisów. Zwróć uwagę na strony świata i doświetlenie, wysokość pomieszczeń, miejsce na pralkę i szafy oraz na to, co widać z okien. Obejrzyj też części wspólne i otoczenie osiedla o różnych porach dnia – to one decydują o codziennym komforcie."}', 4),
('{"pl":"Ile wkładu własnego potrzebuję, żeby kupić mieszkanie?"}', '{"pl":"Banki zwykle wymagają od 10 do 20% wartości nieruchomości. Do tego warto doliczyć koszty okołozakupowe: taksę notarialną, wpisy sądowe, prowizję banku i wykończenie mieszkania. Wysokość wkładu i dostępne programy najlepiej potwierdzić u doradcy kredytowego – chętnie polecimy sprawdzonego."}', 5),
('{"pl":"Czy mogę negocjować cenę mieszkania z deweloperem?"}', '{"pl":"Ceny mieszkań wynikają z aktualnego cennika inwestycji, ale zawsze warto porozmawiać z biurem sprzedaży. Pole do rozmowy bywa przy konkretnych lokalach, formie płatności czy pakiecie wykończeniowym. Nasi doradcy przedstawią wszystkie dostępne warunki wprost, bez ukrytych kosztów."}', 6),
('{"pl":"Jakie miesięczne koszty ponoszę po zakupie mieszkania?"}', '{"pl":"Na miesięczne koszty składają się czynsz administracyjny (utrzymanie części wspólnych, fundusz remontowy), media rozliczane według liczników oraz rata kredytu, jeśli korzystasz z finansowania. Do tego dochodzi roczny podatek od nieruchomości. Wysokość czynszu dla konkretnej inwestycji poda Ci biuro sprzedaży."}', 7),
('{"en":"1. What does the developer standard include?"}', '{"en":"<p>There is no single legal definition of the developer standard, so its exact scope is always described in the developer specification and the development agreement. In general, an apartment delivered to the developer standard is ready for finishing work. The exact scope may vary depending on the standard of the residential development.<\\/p>\\n                        <p>Our standard includes, among other things, machine-applied gypsum-lime plaster on the walls, floor screeds, complete electrical, water, sewage and heating systems with radiators, as well as kitchen sockets, an RTV + LAN socket and Smart Home installations.<\\/p>"}', 8),
('{"en":"2. What should you check before signing a development agreement?"}', '{"en":"<p>Before signing a development agreement, you should carefully check the Information Prospectus, payment schedule and the final date for the transfer of ownership.<\\/p>\\n                        <p>It is also important to check the exact size of the apartment, any additional areas or facilities included with it, such as a balcony, storage unit or parking space in the underground garage, as well as the finishing standard.<\\/p>\\n                        <p>For a safe purchase of a new apartment from a developer, the development agreement must be signed in the form of a notarial deed.<\\/p>"}', 9),
('{"en":"3. What additional costs are involved when buying an apartment from a developer?"}', '{"en":"<p>When buying a new apartment on the primary market, you do not pay the 2% tax on civil law transactions (PCC), which generally applies to purchases on the secondary market.<\\/p>\\n                        <p>However, there are some additional costs to consider:<\\/p>\\n                        <ul>\\n                            <li><strong>Notary fees<\\/strong> – the notary fee is shared equally between the developer and the buyer. There are also costs for copies of the notarial deed and entries in the Land and Mortgage Register.<\\/li>\\n                            <li><strong>Finishing costs<\\/strong> – you should also plan a budget for finishing the apartment and making it ready to move into.<\\/li>\\n                        <\\/ul>"}', 10),
('{"en":"4. What happens during the technical inspection of an apartment and what should you check?"}', '{"en":"<p>The technical inspection is the moment when you check whether the apartment meets the conditions set out in the development agreement and complies with building standards.<\\/p>\\n                        <p>It is a good idea to bring a spirit level and a laser distance meter or ask a professional engineer to assist you.<\\/p>\\n                        <p>During the inspection, you should check the walls and angles, any scratches on the windows, ventilation, the location of electrical points and the quality of the floor screeds.<\\/p>\\n                        <p>All defects should be recorded in the inspection report. The developer then has a statutory period to respond to the reported defects.<\\/p>"}', 11),
('{"en":"5. Why choose a new apartment instead of one from the secondary market?"}', '{"en":"<p>Buying a new apartment from a developer can save you time and money at the start and gives you the benefits of modern construction.<\\/p>\\n                        <p>New apartments are built according to current building regulations and strict quality standards. When you buy on the primary market, you benefit from a 5-year statutory warranty for defects, modern architecture, underground garages, quiet lifts and energy-saving technologies such as photovoltaic panels and Smart Home systems.<\\/p>\\n                        <p>You also do not pay the 2% PCC tax and have complete freedom to design and finish your new interior from scratch.<\\/p>"}', 12),
('{"en":"6. How can you safely buy a new apartment? What is a Housing Escrow Account?"}', '{"en":"<p>The money paid by customers buying new apartments is protected under the Developer Act.<\\/p>\\n                        <p>Your payments do not go directly to the developer’s bank account. Instead, they are paid into a Housing Escrow Account managed by a bank.<\\/p>\\n                        <p>In the case of an open escrow account, the bank releases the money to the developer in stages. Funds are released only after an independent inspector confirms that a specific stage of construction has been completed. This provides a high level of protection for the buyer’s money.<\\/p>"}', 13),
('{"en":"7. Can I make changes to the layout of my new apartment?"}', '{"en":"<p>Yes. Most developers allow buyers to make changes at an early stage of construction.<\\/p>\\n                        <p>These changes allow you to adapt the apartment to your individual needs. The most common changes include moving partition walls, changing the location of electrical points such as lights and sockets, and modifying water and sewage connections, for example replacing a bathtub with a shower.<\\/p>\\n                        <p>Making these changes early can help you avoid expensive modifications when finishing the apartment later.<\\/p>"}', 14),
('{"en":"8. How much does it cost to finish an apartment per square metre?"}', '{"en":"<p>The cost of finishing an apartment depends on the materials you choose and the rates charged by the finishing company.<\\/p>\\n                        <p>As a general estimate, basic finishing costs start at around <strong>PLN 2,000 per square metre<\\/strong>, including labour and materials.<\\/p>\\n                        <p>For premium interiors with high-quality materials and custom-made furniture, the total cost can be much higher.<\\/p>"}', 15),
('{"en":"9. How does buying a new apartment with a mortgage work?"}', '{"en":"<p>Buying an apartment with mortgage financing can be divided into a few simple steps:<\\/p>\\n                        <ol>\\n                            <li>Check your mortgage eligibility with a financial advisor and choose your apartment.<\\/li>\\n                            <li>Sign a reservation agreement with the developer.<\\/li>\\n                            <li>Apply for a mortgage and submit the required technical documents provided by the developer.<\\/li>\\n                            <li>Sign the development agreement and the mortgage agreement with the bank.<\\/li>\\n                            <li>The bank releases the mortgage funds in stages according to the progress of construction.<\\/li>\\n                        <\\/ol>"}', 16),
('{"en":"10. How long is the statutory warranty for a new apartment and what does it cover?"}', '{"en":"<p>Under the Polish Civil Code, the statutory warranty for a new apartment is <strong>5 years from the date the apartment is handed over to the buyer<\\/strong>.<\\/p>\\n                        <p>The developer is responsible for physical defects in the property. If a defect is discovered during this period, the owner has the right to ask the developer to repair it.<\\/p>"}', 17),
('{"en":"11. How to choose an apartment for a single person?"}', '{"en":"<p>When choosing an apartment for one person, it is worth considering a compact and functional studio or a small one-bedroom apartment.<\\/p>\\n                        <p>Location is very important. Good access to the city centre, public transport, shops and services makes everyday life easier.<\\/p>\\n                        <p>Smart Home systems are also a great advantage, improving both comfort and security. If you are looking for an apartment for one person in Olsztyn, <strong>TEMPO at Sikorskiego Street<\\/strong> is a good option for people with an active lifestyle.<\\/p>"}', 18),
('{"en":"12. What should an apartment for a senior offer?"}', '{"en":"<p>An apartment for a senior should be safe, functional and free from architectural barriers.<\\/p>\\n                        <p>An important feature is a modern lift with direct access to the underground garage and storage units, as well as step-free access to the building.<\\/p>\\n                        <p>Easy access to medical centres, pharmacies, shops and public transport is also important. A senior-friendly development should also offer quiet green areas with benches and monitoring for greater safety.<\\/p>"}', 19),
('{"en":"13. What do families with children look for when choosing an apartment?"}', '{"en":"<p>For families with children, the main priorities are safety, space and easy access to schools, kindergartens, medical centres and shops.<\\/p>\\n                        <p>Safe and monitored green areas with walking paths, playgrounds and sports areas are also very important, as they provide space for families to spend time outdoors.<\\/p>\\n                        <p>Families also value environmentally friendly solutions that can help reduce everyday running costs. A good example in Olsztyn is the <strong>SLOW development<\\/strong>, designed with family comfort in mind.<\\/p>"}', 20),
('{"en":"14. What green areas and shared facilities do modern residential developments offer?"}', '{"en":"<p>Modern residential developments provide shared spaces designed for relaxation, recreation and spending time together.<\\/p>\\n                        <p>For example, the <strong>SLOW development in Olsztyn<\\/strong> offers an outdoor yoga area, a barbecue shelter with tables and a professional agility area for dogs.<\\/p>\\n                        <p>Residents can also use safe playgrounds, rain gardens, electric vehicle charging stations and bicycle shelters.<\\/p>"}', 21);
